### ISSUE TITLE
Wrong HSTS header detection when multiple redirects involved

### ISSUE THREAD

**Issue by nextPrime** [chromium/hstspreload.appspot.com#36]
Here is an [example](https://hstspreload.appspot.com/?domain=wmfusercontent.org): http://wmfusercontent.org redirects to https://wmfusercontent.org, which then redirects to https://www.wikimedia.org. https://wmfusercontent.org sets the HSTS header with `includeSubDomain` and `preload`, which I believe satisfy all requirements for preloading, although https://www.wikimedia.org doesn't set includeSubDomain directive. But the error message says:
> HTTP redirects to a page without HSTS
> `http://wmfusercontent.org` redirects to `https://wmfusercontent.org/`, which does not serve a HSTS header that satisfies preload conditions. First error: No includeSubDomains directive

Could you please clarify the requirements or is the error message wrong? Thanks!

**Comment by lgarron** [comment]
Hmm, it seems you're right; there is probably a bug. I'll look into it right now.

**Comment by lgarron** [comment]
You should be able to submit now; thanks for the report!
