### ISSUE TITLE
API returns preloaded "No" for subdomains where parent domain is preloaded

### ISSUE THREAD

**Issue by marumari** [chromium/hstspreload.appspot.com#52]
If I do a query for gist.github.com, it will say that it's not preloaded, even though the parent domain (github.com) is preloaded.

This is a bit confusing because the HTTP Observatory says that it's pinned (which it is, because includeSubDomains is set with preload), but the hstspreload results say that it isn't.

Also, I have just some general curmudgeonly issues about the response being "Yes" or "No", instead of a boolean.  That said, a great option would be "Yes", "No", and "viaParentDomain" or something like that.

**Comment by marumari** [comment]
https://mozilla.github.io/http-observatory-website/analyze.html?host=gist.github.com

Is a fine example of where hstspreload and the HTTP Observatory contradict each other.

**Comment by lgarron** [comment]
Yeah, this is currently working as intended because I wanted to keep things as simple as possible.

However, in this case it seems strictly better to report if a parent domain is preloaded.

**Comment by lgarron** [comment]
Moved to https://github.com/chromium/hstspreload/issues/85.

**Comment by april** [comment]
Woohoo! Double high-fives all around!
