### ISSUE TITLE
Doesn't support modern ciphers

### ISSUE THREAD

**Issue by Seegras** [chromium/hstspreload.appspot.com#61]
For example: https://hstspreload.appspot.com/?domain=seegras.discordia.ch will return a handshake failure. Reason is most probably that, if you look at the cipher-list: https://www.ssllabs.com/ssltest/analyze.html?d=seegras.discordia.ch&s=2a05%3afc84%3ac%3a0%3a0%3a0%3a0%3a8&latest your test probably does not support modern ciphers. Either that, or you're having a problem with IPv6 and/or SNI.

**Comment by lgarron** [comment]
https://hstspreload.appspot.com/?domain=seegras.discordia.ch connects now. Did you change a setting?

One issue that has been preventing connections is HTTP/2: #57.

Feel free to re-open if you still see issues.
