### ISSUE TITLE
Obtaining list

### ISSUE THREAD

**Issue by daurnimator** [chromium/hstspreload.appspot.com#65]
Not sure if this is the correct place to ask:
Where can I obtain the HSTS preload list for inclusion in my own software?

**Comment by lgarron** [comment]
If you just want to fetch a file, use the base-64 encoded version at https://chromium.googlesource.com/chromium/src/+/master/net/http/transport_security_state_static.json?format=TEXT

May I ask what you're planning to use it for?
I've been thinking that I should start a registry of downstream preload list consumers, so that I know how it's being used (and can evaluate how any potential changes might affect them).

**Comment by daurnimator** [comment]
https://github.com/daurnimator/lua-http/issues/45

I was thinking it might be good to come up with a "standard" Unix location for the HSTS list. So that all tools can use the one list, and distros will be able to push out updates.

**Comment by lgarron** [comment]
> daurnimator/lua-http#45

Thanks!

> a "standard" Unix location for the HSTS list

😳
The preload list is very much targeted at browsers right now, but it's good to mind that other clients are using this more and more. Trying to use a single store for an entire system is likely to run into problems down the road, but I can see the desire to unify and use something consistent.

**Comment by daurnimator** [comment]
I would expect it to be treated the same as e.g. ca certs. 

I would hope that in future all tools that take http uris from user input would use the HSTS preload list. e.g. curl, wget, python-requests...

**Comment by lgarron** [comment]
> I would expect it to be treated the same as e.g. ca certs.

Many person-centuries have been spent on that system, and it still has many flaws. ;-)

> I would hope that in future all tools that take http uris from user input would use the HSTS preload list. e.g. curl, wget, python-requests...

I actually have a hard time forming an opinion on that.
On one hand, sometimes you're simply fetching or scraping a page, and would probably prefer to receive it securely.
But as a developer, you sometimes need to connect over HTTP to check some behaviour or other. (In particular, you need to connect over HTTP to verify if a site is redirecting to HTTPS correctly).

You either need to make the HSTS semantics opt-in (not much protection), or make the entire stack handle selective HSTS opt-out (and update all legacy software to be aware of the opt-out if they need it – probably impossible).

There is probably a pragmatic middle-ground (e.g. only apply when the scheme is not specified, only apply when clearly called from an interactive session), but I'm wary of edge cases for that, too.

**Comment by daurnimator** [comment]
What I did in lua-http was give request objects a default HSTS store. If you don't want HSTS for a certain request, then either give it a null HSTS store, or a different one.
